// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toxvjcpqjucomvwmvlgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveHZqY3BxanVjb212d212bGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NTI3NjYsImV4cCI6MjA1MjMyODc2Nn0.4SgI8p9YbhNvVi78FpLZKCLsBMMwzHMVLYeDiGeaHKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);